/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

var debug = false;

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/Leberzirrhose.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh onClick={async (e) => debug && await navigator.clipboard.writeText(JSON.stringify(Object.values(e.intersections[0].point)))} geometry={nodes.Leberzirrhose.geometry} material={materials.material_0} position={[0, 0.03, 0]} />
    </group>
  );
}

useGLTF.preload('/Leberzirrhose.glb');