/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Leberzirrhose(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/Leberzirrhose.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={false}
        far={100}
        near={0.1}
        fov={28.84}
        position={[0.57, 0.19, 0.08]}
        rotation={[-1.21, 1.22, 1.18]}
        scale={[10, 10, 10]}
      />
      <mesh geometry={nodes.Leberzirrhose.geometry} material={materials.material_0} position={[0, 0.03, 0]} />
    </group>
  )
}

useGLTF.preload('/Leberzirrhose.glb')
