/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/glb/Leberzirrhose.glb');

  return (
    <group ref={group} {...props} dispose={null}>
      {/* eslint-disable-next-line no-undef */}
      <mesh onClick={async (e) => process.env.NODE_ENV === 'development' && await navigator.clipboard.writeText(JSON.stringify(Object.values(e.intersections[0].point)))} geometry={nodes.Leberzirrhose.geometry} material={materials.material_0} position={[0, 0.03, 0]} />
    </group>
  );
}

useGLTF.preload('/Leberzirrhose.glb');